Newtext+Images
UWFormulaN/Website pull request #11
Opened 2024-11-14 20:43 UTC by jasminetey

new images added were touched up and replaced placeholder text, changed the stairs photo to cropped one but you can change it back to the uncropped if it looks better

2024-11-14 22:09 UTC, bergermaestro commented
looks good! a few thoughts:
- When I made the Support page, the first paragraph was just a copy/paste from the about page, could you write something more relevant for that page, or just get rid of that first paragraph altogether?
<img width="548" alt="image" src="https://github.com/user-attachments/assets/d4523a98-f80f-4819-bd79-17e65efd0c9f">

(If you you can get this done Friday great, otherwise don't worry about it and we can follow up in a separate pull request later)
- The new images look a bit dark, would it be possible to bump up the exposure on them?
- Please delete any of the picture files that you don't end up using 
- What was your thought process on re-cropping the stairwell picture? I think it looks a bit strange with everyone so close to the bottom, but am open to it

2024-11-14 22:17 UTC, bergermaestro requested changes

2024-11-14 22:17 UTC, bergermaestro commented on src/components/JoinAccordion.tsx
> +          <ul className= "list-disc list-inside ml-100 mt-2 ">
`ml-100` is not a valid class - it's not doing anything

2024-11-14 22:17 UTC, bergermaestro commented on src/components/JoinAccordion.tsx
> +          <ol className= "list-decimal list-inside ml-100 space-y-2 mt-2 ">
same comment about `ml-100`

2024-11-14 22:19 UTC, bergermaestro commented on src/pages/index.astro
> +          date="August 2024"
This should be Fall 2023

2024-11-14 22:38 UTC, jasminetey commented on src/pages/index.astro
> +          date="August 2024"
whoops supposed to write august 2023- ill change to fall 2023

2024-11-15 01:17 UTC, bergermaestro approved these changes

2024-11-15 01:17 UTC, merged